export function formatPrice(price: number, currency: string): string {
  return new Intl.NumberFormat("en-US", { style: "currency", currency }).format(price);
}

export function getWhatsAppUrl(phoneNumber: string, productName?: string): string {
  const text = productName
    ? `Hi, I'm interested in: ${productName}. Can you share more details?`
    : "Hi, I'd like to know more about your products.";
  return `https://wa.me/${phoneNumber}?text=${encodeURIComponent(text)}`;
}

export const WHATSAPP_NUMBER = "18609609600";
export const BRAND_EMAIL = "hello@dealbazaar.ai";

/**
 * Return a URL suitable for thumbnails. For locally-served product images
 * (/images/products/...) we have a pre-built -400.jpg variant generated by
 * scripts/generate-products.ts. Anything else (Supabase URLs, /jewelry, etc)
 * passes through unchanged.
 */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
export function thumbnailUrl(url: string, width = 400): string {
  if (!url) return url;
  const match = url.match(
    /^(\/images\/products\/[^/]+\/)([^/]+)\.(jpg|jpeg|png|webp)$/i
  );
  if (match) {
    return `${match[1]}${match[2]}-400.jpg`;
  }
  return url;
}
